import { createClient } from "@supabase/supabase-js";
import { generateWorkoutContent } from "@/lib/workout/generate.server";
import { complianceIssues } from "@/lib/workout/smarty-compliance";
const U = require("fs").readFileSync(".env","utf8").match(/VITE_SUPABASE_URL="?([^"\n]+)/)[1];
const db = createClient(U, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
const lib = [...require("/tmp/wu/e0.json"), ...require("/tmp/wu/e1000.json")].filter((e: any) => e.is_active !== false);
const [cat, min, stars, ...eq] = process.argv.slice(2);
const r = await generateWorkoutContent(db as never, { category: cat, format: null, equipmentMode: eq[0]==="bodyweight"?"BODYWEIGHT":"EQUIPMENT", selectedEquipment: eq, stars: +stars, minutes: +min, focus: null, location: eq[0]==="bodyweight"?"anywhere":"gym", deterministic: true } as never, []);
console.log(r.warnings);
console.log(r.main_workout.replace(/<[^>]+>/g, " ").replace(/\s+/g, " "));
console.log(complianceIssues({ id:"x", name:"x", category:cat, format:r.format, difficulty_stars:+stars, duration_min:+min, equipment:eq, main_workout:r.main_workout }, lib));
