// THE SmartyGym Strength & Muscle Building exercise selection (set by Haris Falas).
// Any STRENGTH or MUSCLE BUILDING workout that uses equipment draws its Main
// Workout and Finisher ONLY from these 100 exercises (50 machines + 50 free
// weights). Bodyweight-only Strength workouts keep the general rules.
// Activation and Cool Down keep their own prep vocabulary (prep-vocabulary.ts).
// Read by rules.ts, so the pool filter, validator, admin publish gate and the
// stored-workout audit all apply the same list.
// `library` is the exercise-library name the entry resolves to (null = not in
// the library yet, so it can never be programmed until it is added).

export const STRENGTH_EXERCISES: ReadonlyArray<{ name: string; library: string | null; group: "machine" | "free" }> = [
  { name: "Lever Leg Extension", library: "lever leg extension", group: "machine" },
  { name: "Lever Lying Leg Curl", library: "lever lying leg curl", group: "machine" },
  { name: "Lever Seated Leg Curl", library: "lever seated leg curl", group: "machine" },
  { name: "Sled 45° Leg Press", library: "sled 45\u00b0 leg press", group: "machine" },
  { name: "Sled 45° Leg Wide Press", library: "sled 45\u00b0 leg wide press", group: "machine" },
  { name: "Sled Hack Squat", library: "sled hack squat", group: "machine" },
  { name: "Lever Alternate Leg Press", library: "lever alternate leg press", group: "machine" },
  { name: "Lever Horizontal One Leg Press", library: "lever horizontal one leg press", group: "machine" },
  { name: "Lever Hip Extension v. 2", library: "lever hip extension v. 2", group: "machine" },
  { name: "Lever Seated Hip Abduction", library: "lever seated hip abduction", group: "machine" },
  { name: "Lever Seated Hip Adduction", library: "lever seated hip adduction", group: "machine" },
  { name: "Lever Standing Calf Raise", library: "lever standing calf raise", group: "machine" },
  { name: "Lever Seated Calf Raise", library: "lever seated calf raise", group: "machine" },
  { name: "Lever Calf Press", library: "lever calf press", group: "machine" },
  { name: "Lever Chest Press", library: "lever chest press", group: "machine" },
  { name: "Lever Incline Chest Press", library: "lever incline chest press", group: "machine" },
  { name: "Lever Decline Chest Press", library: "lever decline chest press", group: "machine" },
  { name: "Lever Seated Fly", library: "lever seated fly", group: "machine" },
  { name: "Lever Front Pulldown", library: "lever front pulldown", group: "machine" },
  { name: "Reverse Grip Machine Lat Pulldown", library: "reverse grip machine lat pulldown", group: "machine" },
  { name: "Lever Seated Row", library: "lever seated row", group: "machine" },
  { name: "Lever Narrow Grip Seated Row", library: "lever narrow grip seated row", group: "machine" },
  { name: "Lever High Row", library: "lever high row", group: "machine" },
  { name: "Lever T-Bar Row", library: "lever t bar row", group: "machine" },
  { name: "Lever Reverse Grip Vertical Row", library: "lever reverse grip vertical row", group: "machine" },
  { name: "Lever Shoulder Press", library: "lever shoulder press", group: "machine" },
  { name: "Lever Lateral Raise", library: "lever lateral raise", group: "machine" },
  { name: "Lever Seated Reverse Fly", library: "lever seated reverse fly", group: "machine" },
  { name: "Lever Preacher Curl", library: "lever preacher curl", group: "machine" },
  { name: "Lever Bicep Curl", library: "lever bicep curl", group: "machine" },
  { name: "Lever Triceps Extension", library: "lever triceps extension", group: "machine" },
  { name: "Cable Lat Pulldown Full Range of Motion", library: "cable lat pulldown full range of motion", group: "machine" },
  { name: "Cable Low Seated Row", library: "cable low seated row", group: "machine" },
  { name: "Cable Seated Row", library: "cable seated row", group: "machine" },
  { name: "Cable Straight Back Seated Row", library: "cable straight back seated row", group: "machine" },
  { name: "Cable Seated Chest Press", library: "cable seated chest press", group: "machine" },
  { name: "Cable Shoulder Press", library: "cable shoulder press", group: "machine" },
  { name: "Cable Lateral Raise", library: "cable lateral raise", group: "machine" },
  { name: "Cable Seated Rear Lateral Raise", library: "cable seated rear lateral raise", group: "machine" },
  { name: "Cable Preacher Curl", library: "cable preacher curl", group: "machine" },
  { name: "Cable One Arm Preacher Curl", library: "cable one arm preacher curl", group: "machine" },
  { name: "Cable Triceps Pushdown (V-Bar)", library: "cable triceps pushdown (v-bar)", group: "machine" },
  { name: "Cable Overhead Triceps Extension (Rope Attachment)", library: "cable overhead triceps extension (rope attachment)", group: "machine" },
  { name: "Cable Standing One Arm Triceps Extension", library: "cable standing one arm triceps extension", group: "machine" },
  { name: "Cable Hip Adduction", library: "cable hip adduction", group: "machine" },
  { name: "Cable Standing Calf Raise", library: "cable standing calf raise", group: "machine" },
  { name: "Cable Standing One Leg Calf Raise", library: "cable standing one leg calf raise", group: "machine" },
  { name: "Ab Crunch Machine", library: "ab crunch machine", group: "machine" },
  { name: "Lever Seated Crunch", library: "lever seated crunch", group: "machine" },
  { name: "Lever Back Extension", library: "lever back extension", group: "machine" },
  { name: "Barbell Bench Press", library: "barbell bench press", group: "free" },
  { name: "Barbell Incline Bench Press", library: "barbell incline bench press", group: "free" },
  { name: "Barbell Wide Bench Press", library: "barbell wide bench press", group: "free" },
  { name: "Barbell Decline Bench Press", library: "barbell decline bench press", group: "free" },
  { name: "Barbell Bent Over Row", library: "barbell bent over row", group: "free" },
  { name: "Barbell Pendlay Row", library: "barbell pendlay row", group: "free" },
  { name: "Barbell Romanian Deadlift", library: "barbell romanian deadlift", group: "free" },
  { name: "Barbell Deadlift", library: "barbell deadlift", group: "free" },
  { name: "Barbell Front Squat", library: "barbell front squat", group: "free" },
  { name: "Barbell Back Squat", library: "barbell full squat", group: "free" },
  { name: "Barbell Sumo Deadlift", library: "barbell sumo deadlift", group: "free" },
  { name: "Barbell Hip Thrust", library: "barbell glute bridge", group: "free" },
  { name: "Barbell Seated Overhead Press", library: "barbell seated overhead press", group: "free" },
  { name: "Barbell Standing Military Press", library: "barbell standing wide military press", group: "free" },
  { name: "Barbell Upright Row", library: "barbell upright row", group: "free" },
  { name: "Barbell Rear Delt Raise", library: "barbell rear delt raise", group: "free" },
  { name: "Barbell Shrug", library: "barbell shrug", group: "free" },
  { name: "Barbell Close-Grip Bench Press", library: "barbell close-grip bench press", group: "free" },
  { name: "Barbell Standing Overhead Triceps Extension", library: "barbell standing overhead triceps extension", group: "free" },
  { name: "Barbell Preacher Curl", library: "barbell preacher curl", group: "free" },
  { name: "Dumbbell Bench Press", library: "dumbbell bench press", group: "free" },
  { name: "Dumbbell Incline Bench Press", library: "dumbbell incline bench press", group: "free" },
  { name: "Dumbbell Fly", library: "dumbbell fly", group: "free" },
  { name: "Dumbbell Bent Over Row", library: "dumbbell bent over row", group: "free" },
  { name: "Dumbbell Shoulder Press", library: "dumbbell seated shoulder press", group: "free" },
  { name: "Dumbbell Arnold Press", library: "dumbbell arnold press", group: "free" },
  { name: "Dumbbell Lateral Raise", library: "dumbbell lateral raise", group: "free" },
  { name: "Dumbbell Upright Row", library: "dumbbell upright row", group: "free" },
  { name: "Dumbbell Rear Lateral Raise", library: "dumbbell rear lateral raise", group: "free" },
  { name: "Dumbbell Biceps Curl", library: "dumbbell biceps curl", group: "free" },
  { name: "Dumbbell Hammer Curl", library: "dumbbell hammer curl", group: "free" },
  { name: "Dumbbell Preacher Curl", library: "dumbbell preacher curl", group: "free" },
  { name: "Dumbbell Triceps Extension", library: "dumbbell standing triceps extension", group: "free" },
  { name: "Dumbbell Goblet Squat", library: "dumbbell goblet squat", group: "free" },
  { name: "Dumbbell Romanian Deadlift", library: "dumbbell romanian deadlift", group: "free" },
  { name: "Dumbbell Bulgarian Split Squat", library: "dumbbell single leg split squat", group: "free" },
  { name: "Dumbbell Single Leg Deadlift", library: "dumbbell single leg deadlift", group: "free" },
  { name: "Dumbbell Lunges", library: "dumbbell lunge", group: "free" },
  { name: "Dumbbell Standing Calf Raise", library: "dumbbell standing calf raise", group: "free" },
  { name: "Dumbbell Shrug", library: "dumbbell shrug", group: "free" },
  { name: "Kettlebell Goblet Squat", library: "kettlebell goblet squat", group: "free" },
  { name: "Kettlebell Front Squat", library: "kettlebell front squat", group: "free" },
  { name: "Kettlebell One Arm Row", library: "kettlebell one arm row", group: "free" },
  { name: "Kettlebell Two Arm Row", library: "kettlebell two arm row", group: "free" },
  { name: "Kettlebell One Arm Floor Press", library: "kettlebell one arm floor press", group: "free" },
  { name: "Kettlebell Two Arm Military Press", library: "kettlebell two arm military press", group: "free" },
  { name: "Kettlebell One Arm Push Press", library: "kettlebell one arm push press", group: "free" },
  { name: "Kettlebell Swing", library: "kettlebell swing", group: "free" },
  { name: "Kettlebell Romanian Deadlift", library: null, group: "free" },
  { name: "Kettlebell Lunge Pass Through", library: "kettlebell lunge pass through", group: "free" },
];

const norm = (s: string) => s.toLowerCase().replace(/°/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const NAMES = new Set(STRENGTH_EXERCISES.flatMap((e) => (e.library ? [norm(e.library), norm(e.name)] : [])));

/** True only for exercises on the SmartyGym Strength & Muscle Building list. */
export const isStrengthListExercise = (e: { name: string }) => NAMES.has(norm(e.name));

export const STRENGTH_LIST_NAMES = STRENGTH_EXERCISES.filter((e) => e.library).map((e) => e.name);
