// THE SmartyGym Strength & Muscle Hypertrophy exercise selection (set by Haris Falas).
// STRENGTH and MUSCLE BUILDING Main Workout + Finisher draw ONLY from this list:
//   - bodyweight workouts: the 50 "bodyweight" entries (pool A)
//   - equipment / gym workouts: the 50 gym machines + the 50 free-weight /
//     equipment entries (pool B); bodyweight entries are not mixed in.
// Activation and Cool Down keep their own prep vocabulary (prep-vocabulary.ts).
// Read by rules.ts, so the pool filter, validator, admin publish gate and the
// stored-workout audit all apply the same list.
// `library` is the exercise-library name the entry resolves to (null = not in
// the library, so it can never be programmed until it is added).

export type StrengthGroup = "bodyweight" | "machine" | "free";
export const STRENGTH_EXERCISES: ReadonlyArray<{ name: string; library: string | null; group: StrengthGroup }> = [
  { name: "Push-Up", library: "push-up", group: "bodyweight" },
  { name: "Incline Push-Up", library: "incline push-up", group: "bodyweight" },
  { name: "Decline Push-Up", library: "decline push-up", group: "bodyweight" },
  { name: "Diamond Push-Up", library: "diamond push-up", group: "bodyweight" },
  { name: "Pike Push-Up", library: null, group: "bodyweight" },
  { name: "Bodyweight Squat", library: "quads (bodyweight squat)", group: "bodyweight" },
  { name: "Bulgarian Split Squat", library: null, group: "bodyweight" },
  { name: "Reverse Lunge", library: null, group: "bodyweight" },
  { name: "Forward Lunge", library: "forward lunge", group: "bodyweight" },
  { name: "Side Lunge", library: null, group: "bodyweight" },
  { name: "Walking Lunge", library: "walking lunge", group: "bodyweight" },
  { name: "Single-Leg Squat", library: "one leg squat", group: "bodyweight" },
  { name: "Pistol Squat", library: "single leg squat (pistol) male", group: "bodyweight" },
  { name: "Step-Up", library: null, group: "bodyweight" },
  { name: "Glute Bridge", library: "glute bridge", group: "bodyweight" },
  { name: "Single-Leg Glute Bridge", library: "single leg bridge with outstretched leg", group: "bodyweight" },
  { name: "Hip Thrust", library: null, group: "bodyweight" },
  { name: "Single-Leg Hip Thrust", library: null, group: "bodyweight" },
  { name: "Nordic Hamstring Curl", library: "inverse leg curl (bench support)", group: "bodyweight" },
  { name: "Single-Leg Romanian Deadlift", library: null, group: "bodyweight" },
  { name: "Calf Raise", library: "bodyweight standing calf raise", group: "bodyweight" },
  { name: "Single-Leg Calf Raise", library: "one leg floor calf raise", group: "bodyweight" },
  { name: "Plank", library: "plank", group: "bodyweight" },
  { name: "Side Plank", library: "side bridge v. 2", group: "bodyweight" },
  { name: "Reverse Plank", library: null, group: "bodyweight" },
  { name: "Bodyweight Row", library: "inverted row", group: "bodyweight" },
  { name: "TRX Row", library: "suspended row", group: "bodyweight" },
  { name: "TRX Push-Up", library: "suspended push-up", group: "bodyweight" },
  { name: "TRX Squat", library: null, group: "bodyweight" },
  { name: "TRX Lunge", library: "suspended split squat", group: "bodyweight" },
  { name: "TRX Single-Leg Squat", library: null, group: "bodyweight" },
  { name: "TRX Hamstring Curl", library: null, group: "bodyweight" },
  { name: "TRX Hip Press", library: null, group: "bodyweight" },
  { name: "TRX Pike", library: null, group: "bodyweight" },
  { name: "TRX Atomic Push-Up", library: null, group: "bodyweight" },
  { name: "Mountain Climber", library: "mountain climber", group: "bodyweight" },
  { name: "Bear Crawl", library: "bear crawl", group: "bodyweight" },
  { name: "Sit-Up", library: "sit-up v. 2", group: "bodyweight" },
  { name: "Crunch", library: "crunch floor", group: "bodyweight" },
  { name: "Reverse Crunch", library: "reverse crunch", group: "bodyweight" },
  { name: "Bicycle Crunch", library: "bicycle crunch", group: "bodyweight" },
  { name: "Leg Raise", library: "lying leg raise flat bench", group: "bodyweight" },
  { name: "Hanging Knee Raise", library: null, group: "bodyweight" },
  { name: "Hanging Leg Raise", library: "hanging leg raise", group: "bodyweight" },
  { name: "Dead Bug", library: "dead bug", group: "bodyweight" },
  { name: "Bird Dog", library: "bird dog", group: "bodyweight" },
  { name: "Superman", library: null, group: "bodyweight" },
  { name: "Back Extension", library: "hyperextension", group: "bodyweight" },
  { name: "Side Crunch", library: "oblique crunches floor", group: "bodyweight" },
  { name: "Russian Twist", library: "russian twist", group: "bodyweight" },
  { name: "Lever Leg Extension", library: "lever leg extension", group: "machine" },
  { name: "Lever Lying Leg Curl", library: "lever lying leg curl", group: "machine" },
  { name: "Lever Seated Leg Curl", library: "lever seated leg curl", group: "machine" },
  { name: "Sled 45° Leg Press", library: "sled 45\u00b0 leg press", group: "machine" },
  { name: "Sled 45° Leg Wide Press", library: "sled 45\u00b0 leg wide press", group: "machine" },
  { name: "Sled Hack Squat", library: "sled hack squat", group: "machine" },
  { name: "Lever Alternate Leg Press", library: "lever alternate leg press", group: "machine" },
  { name: "Lever Horizontal One Leg Press", library: "lever horizontal one leg press", group: "machine" },
  { name: "Lever Hip Extension v. 2", library: "lever hip extension v. 2", group: "machine" },
  { name: "Lever Seated Hip Abduction", library: "lever seated hip abduction", group: "machine" },
  { name: "Lever Seated Hip Adduction", library: "lever seated hip adduction", group: "machine" },
  { name: "Lever Standing Calf Raise", library: "lever standing calf raise", group: "machine" },
  { name: "Lever Seated Calf Raise", library: "lever seated calf raise", group: "machine" },
  { name: "Lever Calf Press", library: "lever calf press", group: "machine" },
  { name: "Lever Chest Press", library: "lever chest press", group: "machine" },
  { name: "Lever Incline Chest Press", library: "lever incline chest press", group: "machine" },
  { name: "Lever Decline Chest Press", library: "lever decline chest press", group: "machine" },
  { name: "Lever Seated Fly", library: "lever seated fly", group: "machine" },
  { name: "Lever Front Pulldown", library: "lever front pulldown", group: "machine" },
  { name: "Reverse Grip Machine Lat Pulldown", library: "reverse grip machine lat pulldown", group: "machine" },
  { name: "Lever Seated Row", library: "lever seated row", group: "machine" },
  { name: "Lever Narrow Grip Seated Row", library: "lever narrow grip seated row", group: "machine" },
  { name: "Lever High Row", library: "lever high row", group: "machine" },
  { name: "Lever T-Bar Row", library: "lever t bar row", group: "machine" },
  { name: "Lever Reverse Grip Vertical Row", library: "lever reverse grip vertical row", group: "machine" },
  { name: "Lever Shoulder Press", library: "lever shoulder press", group: "machine" },
  { name: "Lever Lateral Raise", library: "lever lateral raise", group: "machine" },
  { name: "Lever Seated Reverse Fly", library: "lever seated reverse fly", group: "machine" },
  { name: "Lever Preacher Curl", library: "lever preacher curl", group: "machine" },
  { name: "Lever Bicep Curl", library: "lever bicep curl", group: "machine" },
  { name: "Lever Triceps Extension", library: "lever triceps extension", group: "machine" },
  { name: "Cable Lat Pulldown Full Range of Motion", library: "cable lat pulldown full range of motion", group: "machine" },
  { name: "Cable Low Seated Row", library: "cable low seated row", group: "machine" },
  { name: "Cable Seated Row", library: "cable seated row", group: "machine" },
  { name: "Cable Straight Back Seated Row", library: "cable straight back seated row", group: "machine" },
  { name: "Cable Seated Chest Press", library: "cable seated chest press", group: "machine" },
  { name: "Cable Shoulder Press", library: "cable shoulder press", group: "machine" },
  { name: "Cable Lateral Raise", library: "cable lateral raise", group: "machine" },
  { name: "Cable Seated Rear Lateral Raise", library: "cable seated rear lateral raise", group: "machine" },
  { name: "Cable Preacher Curl", library: "cable preacher curl", group: "machine" },
  { name: "Cable One Arm Preacher Curl", library: "cable one arm preacher curl", group: "machine" },
  { name: "Cable Triceps Pushdown (V-Bar)", library: "cable triceps pushdown (v-bar)", group: "machine" },
  { name: "Cable Overhead Triceps Extension (Rope Attachment)", library: "cable overhead triceps extension (rope attachment)", group: "machine" },
  { name: "Cable Standing One Arm Triceps Extension", library: "cable standing one arm triceps extension", group: "machine" },
  { name: "Cable Hip Adduction", library: "cable hip adduction", group: "machine" },
  { name: "Cable Standing Calf Raise", library: "cable standing calf raise", group: "machine" },
  { name: "Cable Standing One Leg Calf Raise", library: "cable standing one leg calf raise", group: "machine" },
  { name: "Ab Crunch Machine", library: "ab crunch machine", group: "machine" },
  { name: "Lever Seated Crunch", library: "lever seated crunch", group: "machine" },
  { name: "Lever Back Extension", library: "lever back extension", group: "machine" },
  { name: "Barbell Bench Press", library: "barbell bench press", group: "free" },
  { name: "Barbell Incline Bench Press", library: "barbell incline bench press", group: "free" },
  { name: "Barbell Wide Bench Press", library: "barbell wide bench press", group: "free" },
  { name: "Barbell Decline Bench Press", library: "barbell decline bench press", group: "free" },
  { name: "Barbell Bent Over Row", library: "barbell bent over row", group: "free" },
  { name: "Barbell Pendlay Row", library: "barbell pendlay row", group: "free" },
  { name: "Barbell Romanian Deadlift", library: "barbell romanian deadlift", group: "free" },
  { name: "Barbell Deadlift", library: "barbell deadlift", group: "free" },
  { name: "Barbell Front Squat", library: "barbell front squat", group: "free" },
  { name: "Barbell Full Squat", library: "barbell full squat", group: "free" },
  { name: "Barbell Sumo Deadlift", library: "barbell sumo deadlift", group: "free" },
  { name: "Barbell Seated Overhead Press", library: "barbell seated overhead press", group: "free" },
  { name: "Barbell Standing Close Grip Military Press", library: "barbell standing close grip military press", group: "free" },
  { name: "Barbell Standing Wide Military Press", library: "barbell standing wide military press", group: "free" },
  { name: "Barbell Upright Row", library: "barbell upright row", group: "free" },
  { name: "Barbell Rear Delt Row", library: "barbell rear delt row", group: "free" },
  { name: "Barbell Shrug", library: "barbell shrug", group: "free" },
  { name: "Barbell Close-Grip Bench Press", library: "barbell close-grip bench press", group: "free" },
  { name: "Barbell Standing Overhead Triceps Extension", library: "barbell standing overhead triceps extension", group: "free" },
  { name: "Barbell Preacher Curl", library: "barbell preacher curl", group: "free" },
  { name: "Dumbbell Bench Press", library: "dumbbell bench press", group: "free" },
  { name: "Dumbbell Incline Bench Press", library: "dumbbell incline bench press", group: "free" },
  { name: "Dumbbell Bent Over Row", library: "dumbbell bent over row", group: "free" },
  { name: "Dumbbell One Arm Bent-Over Row", library: "dumbbell one arm bent-over row", group: "free" },
  { name: "Dumbbell One Arm Shoulder Press", library: "dumbbell one arm shoulder press", group: "free" },
  { name: "Dumbbell Arnold Press", library: "dumbbell arnold press", group: "free" },
  { name: "Dumbbell Lateral Raise", library: "dumbbell lateral raise", group: "free" },
  { name: "Dumbbell Upright Row", library: "dumbbell upright row", group: "free" },
  { name: "Dumbbell Rear Delt Row", library: "dumbbell rear delt row (shoulder)", group: "free" },
  { name: "Dumbbell Biceps Curl", library: "dumbbell biceps curl", group: "free" },
  { name: "Dumbbell Hammer Curl", library: "dumbbell hammer curl", group: "free" },
  { name: "Dumbbell Seated Biceps Curl", library: "dumbbell seated bicep curl", group: "free" },
  { name: "Dumbbell Triceps Extension", library: "dumbbell standing triceps extension", group: "free" },
  { name: "Dumbbell Goblet Squat", library: "dumbbell goblet squat", group: "free" },
  { name: "Dumbbell Lunge", library: "dumbbell lunge", group: "free" },
  { name: "Dumbbell Rear Lunge", library: "dumbbell rear lunge", group: "free" },
  { name: "Dumbbell Single Leg Split Squat", library: "dumbbell single leg split squat", group: "free" },
  { name: "Dumbbell Single Leg Deadlift", library: "dumbbell single leg deadlift", group: "free" },
  { name: "Dumbbell Squat", library: "dumbbell squat", group: "free" },
  { name: "Dumbbell Step-Up", library: "dumbbell step-up", group: "free" },
  { name: "Kettlebell Goblet Squat", library: "kettlebell goblet squat", group: "free" },
  { name: "Kettlebell Front Squat", library: "kettlebell front squat", group: "free" },
  { name: "Kettlebell One Arm Row", library: "kettlebell one arm row", group: "free" },
  { name: "Kettlebell Two Arm Row", library: "kettlebell two arm row", group: "free" },
  { name: "Kettlebell One Arm Floor Press", library: "kettlebell one arm floor press", group: "free" },
  { name: "Kettlebell Two Arm Military Press", library: "kettlebell two arm military press", group: "free" },
  { name: "Kettlebell One Arm Push Press", library: "kettlebell one arm push press", group: "free" },
  { name: "Kettlebell Swing", library: "kettlebell swing", group: "free" },
  { name: "Farmer's Carry", library: "farmers walk", group: "free" },
  { name: "Medicine Ball Overhead Slam", library: "medicine ball overhead slam", group: "free" },
];

const norm = (s: string) => s.toLowerCase().replace(/°/g, "").replace(/[^a-z0-9]+/g, " ").trim();
const setOf = (pred: (g: StrengthGroup) => boolean) =>
  new Set(STRENGTH_EXERCISES.filter((e) => e.library && pred(e.group)).map((e) => norm(e.library!)));
const ALL = setOf(() => true);
const BODYWEIGHT = setOf((g) => g === "bodyweight");
const EQUIPMENT = setOf((g) => g !== "bodyweight");

/** True for any exercise on the SmartyGym Strength & Muscle Hypertrophy list. */
export const isStrengthListExercise = (e: { name: string }) => ALL.has(norm(e.name));
/** Pool A — bodyweight Strength / Muscle Hypertrophy. */
export const isStrengthBodyweightListExercise = (e: { name: string }) => BODYWEIGHT.has(norm(e.name));
/** Pool B — equipment + gym-machine Strength / Muscle Hypertrophy. */
export const isStrengthEquipmentListExercise = (e: { name: string }) => EQUIPMENT.has(norm(e.name));

export const STRENGTH_BODYWEIGHT_NAMES = STRENGTH_EXERCISES.filter((e) => e.library && e.group === "bodyweight").map((e) => e.name);
export const STRENGTH_LIST_NAMES = STRENGTH_EXERCISES.filter((e) => e.library && e.group !== "bodyweight").map((e) => e.name);
